import Country from "../data/models/country.js";

const data = [
	{ id: 1, code: "AD", image: { src: "ad.svg" }, name: "Andorra", phoneCode: 376 },
	{ id: 2, code: "AE", image: { src: "ae.svg" }, name: "United Arab Emirates", phoneCode: 971 },
	{ id: 3, code: "AF", image: { src: "af.svg" }, name: "Afghanistan", phoneCode: 93 },
	{ id: 4, code: "AG", image: { src: "ag.svg" }, name: "Antigua and Barbuda", phoneCode: 1268 },
	{ id: 5, code: "AI", image: { src: "ai.svg" }, name: "Anguilla", phoneCode: 1264 },
	{ id: 6, code: "AL", image: { src: "al.svg" }, name: "Albania", phoneCode: 355 },
	{ id: 7, code: "AM", image: { src: "am.svg" }, name: "Armenia", phoneCode: 374 },
	{ id: 8, code: "AO", image: { src: "ao.svg" }, name: "Angola", phoneCode: 244 },
	{ id: 9, code: "AQ", image: { src: "aq.svg" }, name: "Antarctica", phoneCode: 672 },
	{ id: 10, code: "AR", image: { src: "ar.svg" }, name: "Argentina", phoneCode: 54 },
	{ id: 11, code: "AS", image: { src: "as.svg" }, name: "American Samoa", phoneCode: 1684 },
	{ id: 12, code: "AT", image: { src: "at.svg" }, name: "Austria", phoneCode: 43 },
	{ id: 13, code: "AU", image: { src: "au.svg" }, name: "Australia", phoneCode: 61 },
	{ id: 14, code: "AW", image: { src: "aw.svg" }, name: "Aruba", phoneCode: 297 },
	{ id: 15, code: "AX", image: { src: "ax.svg" }, name: "Åland Islands", phoneCode: 358 },
	{ id: 16, code: "AZ", image: { src: "az.svg" }, name: "Azerbaijan", phoneCode: 994 },
	{ id: 17, code: "BA", image: { src: "ba.svg" }, name: "Bosnia and Herzegovina", phoneCode: 387 },
	{ id: 18, code: "BB", image: { src: "bb.svg" }, name: "Barbados", phoneCode: 1246 },
	{ id: 19, code: "BD", image: { src: "bd.svg" }, name: "Bangladesh", phoneCode: 880 },
	{ id: 20, code: "BE", image: { src: "be.svg" }, name: "Belgium", phoneCode: 32 },
	{ id: 21, code: "BF", image: { src: "bf.svg" }, name: "Burkina Faso", phoneCode: 226 },
	{ id: 22, code: "BG", image: { src: "bg.svg" }, name: "Bulgaria", phoneCode: 359 },
	{ id: 23, code: "BH", image: { src: "bh.svg" }, name: "Bahrain", phoneCode: 973 },
	{ id: 24, code: "BI", image: { src: "bi.svg" }, name: "Burundi", phoneCode: 257 },
	{ id: 25, code: "BJ", image: { src: "bj.svg" }, name: "Benin", phoneCode: 229 },
	{ id: 26, code: "BL", image: { src: "bl.svg" }, name: "Saint Barthélemy", phoneCode: 590 },
	{ id: 27, code: "BM", image: { src: "bm.svg" }, name: "Bermuda", phoneCode: 1441 },
	{ id: 28, code: "BN", image: { src: "bn.svg" }, name: "Brunei Darussalam", phoneCode: 673 },
	{ id: 29, code: "BO", image: { src: "bo.svg" }, name: "Bolivia", phoneCode: 591 },
	{ id: 30, code: "BQ", image: { src: "bq.svg" }, name: "Bonaire, Sint Eustatius and Saba", phoneCode: 599 },
	{ id: 31, code: "BR", image: { src: "br.svg" }, name: "Brazil", phoneCode: 55 },
	{ id: 32, code: "BS", image: { src: "bs.svg" }, name: "Bahamas", phoneCode: 1242 },
	{ id: 33, code: "BT", image: { src: "bt.svg" }, name: "Bhutan", phoneCode: 975 },
	{ id: 34, code: "BV", image: { src: "bv.svg" }, name: "Bouvet Island", phoneCode: 47 },
	{ id: 35, code: "BW", image: { src: "bw.svg" }, name: "Botswana", phoneCode: 267 },
	{ id: 36, code: "BY", image: { src: "by.svg" }, name: "Belarus", phoneCode: 375 },
	{ id: 37, code: "BZ", image: { src: "bz.svg" }, name: "Belize", phoneCode: 501 },
	{ id: 38, code: "CA", image: { src: "ca.svg" }, name: "Canada", phoneCode: 1 },
	{ id: 39, code: "CC", image: { src: "cc.svg" }, name: "Cocos (Keeling) Islands", phoneCode: 61 },
	{ id: 40, code: "CD", image: { src: "cd.svg" }, name: "Congo", phoneCode: 243 },
	{ id: 41, code: "CF", image: { src: "cf.svg" }, name: "Central African Republic", phoneCode: 236 },
	{ id: 42, code: "CG", image: { src: "cg.svg" }, name: "Congo", phoneCode: 242 },
	{ id: 43, code: "CH", image: { src: "ch.svg" }, name: "Switzerland", phoneCode: 41 },
	{ id: 44, code: "CI", image: { src: "ci.svg" }, name: "Côte D'Ivoire", phoneCode: 225 },
	{ id: 45, code: "CK", image: { src: "ck.svg" }, name: "Cook Islands", phoneCode: 682 },
	{ id: 46, code: "CL", image: { src: "cl.svg" }, name: "Chile", phoneCode: 56 },
	{ id: 47, code: "CM", image: { src: "cm.svg" }, name: "Cameroon", phoneCode: 237 },
	{ id: 48, code: "CN", image: { src: "cn.svg" }, name: "China", phoneCode: 86 },
	{ id: 49, code: "CO", image: { src: "co.svg" }, name: "Colombia", phoneCode: 57 },
	{ id: 50, code: "CR", image: { src: "cr.svg" }, name: "Costa Rica", phoneCode: 506 },
	{ id: 51, code: "CU", image: { src: "cu.svg" }, name: "Cuba", phoneCode: 53 },
	{ id: 52, code: "CV", image: { src: "cv.svg" }, name: "Cape Verde", phoneCode: 238 },
	{ id: 53, code: "CW", image: { src: "cw.svg" }, name: "Curaçao", phoneCode: 599 },
	{ id: 54, code: "CX", image: { src: "cx.svg" }, name: "Christmas Island", phoneCode: 61 },
	{ id: 55, code: "CY", image: { src: "cy.svg" }, name: "Cyprus", phoneCode: 537 },
	{ id: 56, code: "CZ", image: { src: "cz.svg" }, name: "Czech Republic", phoneCode: 420 },
	{ id: 57, code: "DE", image: { src: "de.svg" }, name: "Germany", phoneCode: 49 },
	{ id: 58, code: "DJ", image: { src: "dj.svg" }, name: "Djibouti", phoneCode: 253 },
	{ id: 59, code: "DK", image: { src: "dk.svg" }, name: "Denmark", phoneCode: 45 },
	{ id: 60, code: "DM", image: { src: "dm.svg" }, name: "Dominica", phoneCode: 1767 },
	{ id: 61, code: "DO", image: { src: "do.svg" }, name: "Dominican Republic", phoneCode: 1849 },
	{ id: 62, code: "DZ", image: { src: "dz.svg" }, name: "Algeria", phoneCode: 213 },
	{ id: 63, code: "EC", image: { src: "ec.svg" }, name: "Ecuador", phoneCode: 593 },
	{ id: 64, code: "EE", image: { src: "ee.svg" }, name: "Estonia", phoneCode: 372 },
	{ id: 65, code: "EG", image: { src: "eg.svg" }, name: "Egypt", phoneCode: 20 },
	{ id: 66, code: "EH", image: { src: "eh.svg" }, name: "Western Sahara", phoneCode: 212 },
	{ id: 67, code: "ER", image: { src: "er.svg" }, name: "Eritrea", phoneCode: 291 },
	{ id: 68, code: "ES", image: { src: "es.svg" }, name: "Spain", phoneCode: 34 },
	{ id: 69, code: "ET", image: { src: "et.svg" }, name: "Ethiopia", phoneCode: 251 },
	{ id: 70, code: "FI", image: { src: "fi.svg" }, name: "Finland", phoneCode: 358 },
	{ id: 71, code: "FJ", image: { src: "fj.svg" }, name: "Fiji", phoneCode: 679 },
	{ id: 72, code: "FK", image: { src: "fk.svg" }, name: "Falkland Islands (Malvinas)", phoneCode: 500 },
	{ id: 73, code: "FM", image: { src: "fm.svg" }, name: "Micronesia", phoneCode: 691 },
	{ id: 74, code: "FO", image: { src: "fo.svg" }, name: "Faroe Islands", phoneCode: 298 },
	{ id: 75, code: "FR", image: { src: "fr.svg" }, name: "France", phoneCode: 33 },
	{ id: 76, code: "GA", image: { src: "ga.svg" }, name: "Gabon", phoneCode: 241 },
	{ id: 77, code: "GB", image: { src: "gb.svg" }, name: "United Kingdom", phoneCode: 44 },
	{ id: 78, code: "GD", image: { src: "gd.svg" }, name: "Grenada", phoneCode: 1473 },
	{ id: 79, code: "GE", image: { src: "ge.svg" }, name: "Georgia", phoneCode: 995 },
	{ id: 80, code: "GF", image: { src: "gf.svg" }, name: "French Guiana", phoneCode: 594 },
	{ id: 81, code: "GG", image: { src: "gg.svg" }, name: "Guernsey", phoneCode: 44 },
	{ id: 82, code: "GH", image: { src: "gh.svg" }, name: "Ghana", phoneCode: 233 },
	{ id: 83, code: "GI", image: { src: "gi.svg" }, name: "Gibraltar", phoneCode: 350 },
	{ id: 84, code: "GL", image: { src: "gl.svg" }, name: "Greenland", phoneCode: 299 },
	{ id: 85, code: "GM", image: { src: "gm.svg" }, name: "Gambia", phoneCode: 220 },
	{ id: 86, code: "GN", image: { src: "gn.svg" }, name: "Guinea", phoneCode: 224 },
	{ id: 87, code: "GP", image: { src: "gp.svg" }, name: "Guadeloupe", phoneCode: 590 },
	{ id: 88, code: "GQ", image: { src: "gq.svg" }, name: "Equatorial Guinea", phoneCode: 240 },
	{ id: 89, code: "GR", image: { src: "gr.svg" }, name: "Greece", phoneCode: 30 },
	{ id: 90, code: "GS", image: { src: "gs.svg" }, name: "South Georgia", phoneCode: 500 },
	{ id: 91, code: "GT", image: { src: "gt.svg" }, name: "Guatemala", phoneCode: 502 },
	{ id: 92, code: "GU", image: { src: "gu.svg" }, name: "Guam", phoneCode: 1671 },
	{ id: 93, code: "GW", image: { src: "gw.svg" }, name: "Guinea-Bissau", phoneCode: 245 },
	{ id: 94, code: "GY", image: { src: "gy.svg" }, name: "Guyana", phoneCode: 595 },
	{ id: 95, code: "HK", image: { src: "hk.svg" }, name: "Hong Kong", phoneCode: 852 },
	{ id: 96, code: "HM", image: { src: "hm.svg" }, name: "Heard Island and Mcdonald Islands", phoneCode: 672 },
	{ id: 97, code: "HN", image: { src: "hn.svg" }, name: "Honduras", phoneCode: 504 },
	{ id: 98, code: "HR", image: { src: "hr.svg" }, name: "Croatia", phoneCode: 385 },
	{ id: 99, code: "HT", image: { src: "ht.svg" }, name: "Haiti", phoneCode: 509 },
	{ id: 100, code: "HU", image: { src: "hu.svg" }, name: "Hungary", phoneCode: 36 },
	{ id: 101, code: "ID", image: { src: "id.svg" }, name: "Indonesia", phoneCode: 62 },
	{ id: 102, code: "IE", image: { src: "ie.svg" }, name: "Ireland", phoneCode: 353 },
	{ id: 103, code: "IL", image: { src: "il.svg" }, name: "Israel", phoneCode: 972 },
	{ id: 104, code: "IM", image: { src: "im.svg" }, name: "Isle of Man", phoneCode: 44 },
	{ id: 105, code: "IN", image: { src: "in.svg" }, name: "India", phoneCode: 91 },
	{ id: 106, code: "IO", image: { src: "io.svg" }, name: "British Indian Ocean Territory", phoneCode: 246 },
	{ id: 107, code: "IQ", image: { src: "iq.svg" }, name: "Iraq", phoneCode: 964 },
	{ id: 108, code: "IR", image: { src: "ir.svg" }, name: "Iran", phoneCode: 98 },
	{ id: 109, code: "IS", image: { src: "is.svg" }, name: "Iceland", phoneCode: 354 },
	{ id: 110, code: "IT", image: { src: "it.svg" }, name: "Italy", phoneCode: 39 },
	{ id: 111, code: "JE", image: { src: "je.svg" }, name: "Jersey", phoneCode: 44 },
	{ id: 112, code: "JM", image: { src: "jm.svg" }, name: "Jamaica", phoneCode: 1876 },
	{ id: 113, code: "JO", image: { src: "jo.svg" }, name: "Jordan", phoneCode: 962 },
	{ id: 114, code: "JP", image: { src: "jp.svg" }, name: "Japan", phoneCode: 81 },
	{ id: 115, code: "KE", image: { src: "ke.svg" }, name: "Kenya", phoneCode: 254 },
	{ id: 116, code: "KG", image: { src: "kg.svg" }, name: "Kyrgyzstan", phoneCode: 996 },
	{ id: 117, code: "KH", image: { src: "kh.svg" }, name: "Cambodia", phoneCode: 855 },
	{ id: 118, code: "KI", image: { src: "ki.svg" }, name: "Kiribati", phoneCode: 686 },
	{ id: 119, code: "KM", image: { src: "km.svg" }, name: "Comoros", phoneCode: 269 },
	{ id: 120, code: "KN", image: { src: "kn.svg" }, name: "Saint Kitts and Nevis", phoneCode: 1869 },
	{ id: 121, code: "KP", image: { src: "kp.svg" }, name: "North Korea", phoneCode: 850 },
	{ id: 122, code: "KR", image: { src: "kr.svg" }, name: "South Korea", phoneCode: 82 },
	{ id: 123, code: "KW", image: { src: "kw.svg" }, name: "Kuwait", phoneCode: 965 },
	{ id: 124, code: "KY", image: { src: "ky.svg" }, name: "Cayman Islands", phoneCode: 345 },
	{ id: 125, code: "KZ", image: { src: "kz.svg" }, name: "Kazakhstan", phoneCode: 77 },
	{ id: 126, code: "LA", image: { src: "la.svg" }, name: "Lao People's Democratic Republic", phoneCode: 856 },
	{ id: 127, code: "LB", image: { src: "lb.svg" }, name: "Lebanon", phoneCode: 961 },
	{ id: 128, code: "LC", image: { src: "lc.svg" }, name: "Saint Lucia", phoneCode: 1758 },
	{ id: 129, code: "LI", image: { src: "li.svg" }, name: "Liechtenstein", phoneCode: 423 },
	{ id: 130, code: "LK", image: { src: "lk.svg" }, name: "Sri Lanka", phoneCode: 94 },
	{ id: 131, code: "LR", image: { src: "lr.svg" }, name: "Liberia", phoneCode: 231 },
	{ id: 132, code: "LS", image: { src: "ls.svg" }, name: "Lesotho", phoneCode: 266 },
	{ id: 133, code: "LT", image: { src: "lt.svg" }, name: "Lithuania", phoneCode: 370 },
	{ id: 134, code: "LU", image: { src: "lu.svg" }, name: "Luxembourg", phoneCode: 352 },
	{ id: 135, code: "LV", image: { src: "lv.svg" }, name: "Latvia", phoneCode: 371 },
	{ id: 136, code: "LY", image: { src: "ly.svg" }, name: "Libya", phoneCode: 218 },
	{ id: 137, code: "MA", image: { src: "ma.svg" }, name: "Morocco", phoneCode: 212 },
	{ id: 138, code: "MC", image: { src: "mc.svg" }, name: "Monaco", phoneCode: 377 },
	{ id: 139, code: "MD", image: { src: "md.svg" }, name: "Moldova", phoneCode: 373 },
	{ id: 140, code: "ME", image: { src: "me.svg" }, name: "Montenegro", phoneCode: 382 },
	{ id: 141, code: "MF", image: { src: "mf.svg" }, name: "Saint Martin (French Part)", phoneCode: 590 },
	{ id: 142, code: "MG", image: { src: "mg.svg" }, name: "Madagascar", phoneCode: 261 },
	{ id: 143, code: "MH", image: { src: "mh.svg" }, name: "Marshall Islands", phoneCode: 692 },
	{ id: 144, code: "MK", image: { src: "mk.svg" }, name: "Macedonia", phoneCode: 389 },
	{ id: 145, code: "ML", image: { src: "ml.svg" }, name: "Mali", phoneCode: 223 },
	{ id: 146, code: "MM", image: { src: "mm.svg" }, name: "Myanmar", phoneCode: 95 },
	{ id: 147, code: "MN", image: { src: "mn.svg" }, name: "Mongolia", phoneCode: 976 },
	{ id: 148, code: "MO", image: { src: "mo.svg" }, name: "Macao", phoneCode: 853 },
	{ id: 149, code: "MP", image: { src: "mp.svg" }, name: "Northern Mariana Islands", phoneCode: 1670 },
	{ id: 150, code: "MQ", image: { src: "mq.svg" }, name: "Martinique", phoneCode: 596 },
	{ id: 151, code: "MR", image: { src: "mr.svg" }, name: "Mauritania", phoneCode: 222 },
	{ id: 152, code: "MS", image: { src: "ms.svg" }, name: "Montserrat", phoneCode: 1664 },
	{ id: 153, code: "MT", image: { src: "mt.svg" }, name: "Malta", phoneCode: 356 },
	{ id: 154, code: "MU", image: { src: "mu.svg" }, name: "Mauritius", phoneCode: 230 },
	{ id: 155, code: "MV", image: { src: "mv.svg" }, name: "Maldives", phoneCode: 960 },
	{ id: 156, code: "MW", image: { src: "mw.svg" }, name: "Malawi", phoneCode: 265 },
	{ id: 157, code: "MX", image: { src: "mx.svg" }, name: "Mexico", phoneCode: 52 },
	{ id: 158, code: "MY", image: { src: "my.svg" }, name: "Malaysia", phoneCode: 60 },
	{ id: 159, code: "MZ", image: { src: "mz.svg" }, name: "Mozambique", phoneCode: 258 },
	{ id: 160, code: "NA", image: { src: "na.svg" }, name: "Namibia", phoneCode: 264 },
	{ id: 161, code: "NC", image: { src: "nc.svg" }, name: "New Caledonia", phoneCode: 687 },
	{ id: 162, code: "NE", image: { src: "ne.svg" }, name: "Niger", phoneCode: 227 },
	{ id: 163, code: "NF", image: { src: "nf.svg" }, name: "Norfolk Island", phoneCode: 672 },
	{ id: 164, code: "NG", image: { src: "ng.svg" }, name: "Nigeria", phoneCode: 234 },
	{ id: 165, code: "NI", image: { src: "ni.svg" }, name: "Nicaragua", phoneCode: 505 },
	{ id: 166, code: "NL", image: { src: "nl.svg" }, name: "Netherlands", phoneCode: 31 },
	{ id: 167, code: "NO", image: { src: "no.svg" }, name: "Norway", phoneCode: 47 },
	{ id: 168, code: "NP", image: { src: "np.svg" }, name: "Nepal", phoneCode: 977 },
	{ id: 169, code: "NR", image: { src: "nr.svg" }, name: "Nauru", phoneCode: 674 },
	{ id: 170, code: "NU", image: { src: "nu.svg" }, name: "Niue", phoneCode: 683 },
	{ id: 171, code: "NZ", image: { src: "nz.svg" }, name: "New Zealand", phoneCode: 64 },
	{ id: 172, code: "OM", image: { src: "om.svg" }, name: "Oman", phoneCode: 968 },
	{ id: 173, code: "PA", image: { src: "pa.svg" }, name: "Panama", phoneCode: 507 },
	{ id: 174, code: "PE", image: { src: "pe.svg" }, name: "Peru", phoneCode: 51 },
	{ id: 175, code: "PF", image: { src: "pf.svg" }, name: "French Polynesia", phoneCode: 689 },
	{ id: 176, code: "PG", image: { src: "pg.svg" }, name: "Papua New Guinea", phoneCode: 675 },
	{ id: 177, code: "PH", image: { src: "ph.svg" }, name: "Philippines", phoneCode: 63 },
	{ id: 178, code: "PK", image: { src: "pk.svg" }, name: "Pakistan", phoneCode: 92 },
	{ id: 179, code: "PL", image: { src: "pl.svg" }, name: "Poland", phoneCode: 48 },
	{ id: 180, code: "PM", image: { src: "pm.svg" }, name: "Saint Pierre and Miquelon", phoneCode: 508 },
	{ id: 181, code: "PN", image: { src: "pn.svg" }, name: "Pitcairn", phoneCode: 872 },
	{ id: 182, code: "PR", image: { src: "pr.svg" }, name: "Puerto Rico", phoneCode: 1939 },
	{ id: 183, code: "PS", image: { src: "ps.svg" }, name: "Palestinian Territory", phoneCode: 970 },
	{ id: 184, code: "PT", image: { src: "pt.svg" }, name: "Portugal", phoneCode: 351 },
	{ id: 185, code: "PW", image: { src: "pw.svg" }, name: "Palau", phoneCode: 680 },
	{ id: 186, code: "PY", image: { src: "py.svg" }, name: "Paraguay", phoneCode: 595 },
	{ id: 187, code: "QA", image: { src: "qa.svg" }, name: "Qatar", phoneCode: 974 },
	{ id: 188, code: "RE", image: { src: "re.svg" }, name: "Réunion", phoneCode: 262 },
	{ id: 189, code: "RO", image: { src: "ro.svg" }, name: "Romania", phoneCode: 40 },
	{ id: 190, code: "RS", image: { src: "rs.svg" }, name: "Serbia", phoneCode: 381 },
	{ id: 191, code: "RU", image: { src: "ru.svg" }, name: "Russia", phoneCode: 7 },
	{ id: 192, code: "RW", image: { src: "rw.svg" }, name: "Rwanda", phoneCode: 250 },
	{ id: 193, code: "SA", image: { src: "sa.svg" }, name: "Saudi Arabia", phoneCode: 966 },
	{ id: 194, code: "SB", image: { src: "sb.svg" }, name: "Solomon Islands", phoneCode: 677 },
	{ id: 195, code: "SC", image: { src: "sc.svg" }, name: "Seychelles", phoneCode: 248 },
	{ id: 196, code: "SD", image: { src: "sd.svg" }, name: "Sudan", phoneCode: 249 },
	{ id: 197, code: "SE", image: { src: "se.svg" }, name: "Sweden", phoneCode: 46 },
	{ id: 198, code: "SG", image: { src: "sg.svg" }, name: "Singapore", phoneCode: 65 },
	{ id: 199, code: "SH", image: { src: "sh.svg" }, name: "Saint Helena, Ascension and Tristan Da Cunha", phoneCode: 290 },
	{ id: 200, code: "SI", image: { src: "si.svg" }, name: "Slovenia", phoneCode: 386 },
	{ id: 201, code: "SJ", image: { src: "sj.svg" }, name: "Svalbard and Jan Mayen", phoneCode: 47 },
	{ id: 202, code: "SK", image: { src: "sk.svg" }, name: "Slovakia", phoneCode: 421 },
	{ id: 203, code: "SL", image: { src: "sl.svg" }, name: "Sierra Leone", phoneCode: 232 },
	{ id: 204, code: "SM", image: { src: "sm.svg" }, name: "San Marino", phoneCode: 378 },
	{ id: 205, code: "SN", image: { src: "sn.svg" }, name: "Senegal", phoneCode: 221 },
	{ id: 206, code: "SO", image: { src: "so.svg" }, name: "Somalia", phoneCode: 252 },
	{ id: 207, code: "SR", image: { src: "sr.svg" }, name: "Suriname", phoneCode: 597 },
	{ id: 208, code: "SS", image: { src: "ss.svg" }, name: "South Sudan", phoneCode: 211 },
	{ id: 209, code: "ST", image: { src: "st.svg" }, name: "Sao Tome and Principe", phoneCode: 239 },
	{ id: 210, code: "SV", image: { src: "sv.svg" }, name: "El Salvador", phoneCode: 503 },
	{ id: 211, code: "SX", image: { src: "sx.svg" }, name: "Sint Maarten (Dutch Part)", phoneCode: 721 },
	{ id: 212, code: "SY", image: { src: "sy.svg" }, name: "Syrian Arab Republic", phoneCode: 963 },
	{ id: 213, code: "SZ", image: { src: "sz.svg" }, name: "Swaziland", phoneCode: 268 },
	{ id: 214, code: "TC", image: { src: "tc.svg" }, name: "Turks and Caicos Islands", phoneCode: 1649 },
	{ id: 215, code: "TD", image: { src: "td.svg" }, name: "Chad", phoneCode: 235 },
	{ id: 216, code: "TF", image: { src: "tf.svg" }, name: "French Southern Territories", phoneCode: 262 },
	{ id: 217, code: "TG", image: { src: "tg.svg" }, name: "Togo", phoneCode: 228 },
	{ id: 218, code: "TH", image: { src: "th.svg" }, name: "Thailand", phoneCode: 66 },
	{ id: 219, code: "TJ", image: { src: "tj.svg" }, name: "Tajikistan", phoneCode: 992 },
	{ id: 220, code: "TK", image: { src: "tk.svg" }, name: "Tokelau", phoneCode: 690 },
	{ id: 221, code: "TL", image: { src: "tl.svg" }, name: "Timor-Leste", phoneCode: 670 },
	{ id: 222, code: "TM", image: { src: "tm.svg" }, name: "Turkmenistan", phoneCode: 993 },
	{ id: 223, code: "TN", image: { src: "tn.svg" }, name: "Tunisia", phoneCode: 216 },
	{ id: 224, code: "TO", image: { src: "to.svg" }, name: "Tonga", phoneCode: 676 },
	{ id: 225, code: "TR", image: { src: "tr.svg" }, name: "Turkey", phoneCode: 90 },
	{ id: 226, code: "TT", image: { src: "tt.svg" }, name: "Trinidad and Tobago", phoneCode: 1868 },
	{ id: 227, code: "TV", image: { src: "tv.svg" }, name: "Tuvalu", phoneCode: 688 },
	{ id: 228, code: "TW", image: { src: "tw.svg" }, name: "Taiwan", phoneCode: 886 },
	{ id: 229, code: "TZ", image: { src: "tz.svg" }, name: "Tanzania", phoneCode: 255 },
	{ id: 230, code: "UA", image: { src: "ua.svg" }, name: "Ukraine", phoneCode: 380 },
	{ id: 231, code: "UG", image: { src: "ug.svg" }, name: "Uganda", phoneCode: 256 },
	{ id: 232, code: "US", image: { src: "us.svg" }, name: "United States", phoneCode: 1 },
	{ id: 233, code: "UY", image: { src: "uy.svg" }, name: "Uruguay", phoneCode: 598 },
	{ id: 234, code: "UZ", image: { src: "uz.svg" }, name: "Uzbekistan", phoneCode: 998 },
	{ id: 235, code: "VA", image: { src: "va.svg" }, name: "Vatican City", phoneCode: 379 },
	{ id: 236, code: "VC", image: { src: "vc.svg" }, name: "Saint Vincent and The Grenadines", phoneCode: 1784 },
	{ id: 237, code: "VE", image: { src: "ve.svg" }, name: "Venezuela", phoneCode: 58 },
	{ id: 238, code: "VG", image: { src: "vg.svg" }, name: "Virgin Islands, British", phoneCode: 1284 },
	{ id: 239, code: "VI", image: { src: "vi.svg" }, name: "Virgin Islands, U.S.", phoneCode: 1340 },
	{ id: 240, code: "VN", image: { src: "vn.svg" }, name: "Viet Nam", phoneCode: 84 },
	{ id: 241, code: "VU", image: { src: "vu.svg" }, name: "Vanuatu", phoneCode: 678 },
	{ id: 242, code: "WF", image: { src: "wf.svg" }, name: "Wallis and Futuna", phoneCode: 681 },
	{ id: 243, code: "WS", image: { src: "ws.svg" }, name: "Samoa", phoneCode: 685 },
	{ id: 244, code: "XK", image: { src: "xk.svg" }, name: "Kosovo", phoneCode: 383 },
	{ id: 245, code: "YE", image: { src: "ye.svg" }, name: "Yemen", phoneCode: 967 },
	{ id: 246, code: "YT", image: { src: "yt.svg" }, name: "Mayotte", phoneCode: 262 },
	{ id: 247, code: "ZA", image: { src: "za.svg" }, name: "South Africa", phoneCode: 27 },
	{ id: 248, code: "ZM", image: { src: "zm.svg" }, name: "Zambia", phoneCode: 260 },
	{ id: 249, code: "ZW", image: { src: "zw.svg" }, name: "Zimbabwe", phoneCode: 263 },
];

export default async () => {
	try {
		console.log("Running Country Seeder");

		await Country.deleteMany({});

		data.forEach(async (item) => {
			await Country.create(item);
		});
	} catch (error) {
		console.error("Country Seeding failed:", error);
	}
};
