import Timezone from '../data/models/timezone.js';

const data = [
    {id: 1, name: "(GMT-11:00) International Date Line West", value: "Pacific/Kwajalein"},
    {id: 2, name: "(GMT-11:00) Midway Island", value: "Pacific/Midway"},
    {id: 3, name: "(GMT-11:00) Samoa", value: "Pacific/Samoa"},
    {id: 4, name: "(GMT-10:00) Hawaii", value: "Pacific/Honolulu"},
    {id: 5, name: "(GMT-10:00) Pacific/Honolulu", value: "Pacific/Honolulu"},
    {id: 6, name: "(GMT-09:00) Alaska", value: "US/Alaska"},
    {id: 7, name: "(GMT-08:00) America/Los_Angeles", value: "America/Los_Angeles"},
    {id: 8, name: "(GMT-08:00) Pacific Time (US & Canada)", value: "America/Los_Angeles"},
    {id: 9, name: "(GMT-08:00) Tijuana", value: "America/Tijuana"},
    {id: 10, name: "(GMT-07:00) America/Denver", value: "America/Denver"},
    {id: 11, name: "(GMT-07:00) America/Phoenix", value: "America/Phoenix"},
    {id: 12, name: "(GMT-07:00) Arizona", value: "US/Arizona"},
    {id: 13, name: "(GMT-07:00) Chihuahua", value: "America/Chihuahua"},
    {id: 14, name: "(GMT-07:00) Mazatlan", value: "America/Mazatlan"},
    {id: 15, name: "(GMT-07:00) Mountain Time (US & Canada)", value: "US/Mountain"},
    {id: 16, name: "(GMT-06:00) America/Chicago", value: "America/Chicago"},
    {id: 17, name: "(GMT-06:00) America/Mexico_City", value: "America/Mexico_City"},
    {id: 18, name: "(GMT-06:00) Central America", value: "America/Managua"},
    {id: 19, name: "(GMT-06:00) Central Time (US & Canada)", value: "US/Central"},
    {id: 20, name: "(GMT-06:00) Guadalajara", value: "America/Mexico_City"},
    {id: 21, name: "(GMT-06:00) Mexico City", value: "America/Mexico_City"},
    {id: 22, name: "(GMT-06:00) Monterrey", value: "America/Monterrey"},
    {id: 23, name: "(GMT-06:00) Saskatchewan", value: "Canada/Saskatchewan"},
    {id: 24, name: "(GMT-05:00) America/Nassau", value: "America/Nassau"},
    {id: 25, name: "(GMT-05:00) America/New_York", value: "America/New_York"},
    {id: 26, name: "(GMT-05:00) America/Port-au-Prince", value: "America/Port-au-Prince"},
    {id: 27, name: "(GMT-05:00) America/Toronto", value: "America/Toronto"},
    {id: 28, name: "(GMT-05:00) Bogota", value: "America/Bogota"},
    {id: 29, name: "(GMT-05:00) Eastern Time (US & Canada)", value: "US/Eastern"},
    {id: 30, name: "(GMT-05:00) Indiana (East)", value: "US/East-Indiana"},
    {id: 31, name: "(GMT-05:00) Lima", value: "America/Lima"},
    {id: 32, name: "(GMT-05:00) Quito", value: "America/Bogota"},
    {id: 33, name: "(GMT-04:30) Caracas", value: "America/Caracas"},
    {id: 34, name: "(GMT-04:00) Atlantic Time (Canada)", value: "Canada/Atlantic"},
    {id: 35, name: "(GMT-04:00) Georgetown", value: "America/Argentina/Buenos_Aires"},
    {id: 36, name: "(GMT-04:00) La Paz", value: "America/La_Paz"},
    {id: 37, name: "(GMT-03:30) Newfoundland", value: "Canada/Newfoundland"},
    {id: 38, name: "(GMT-03:00) America/Argentina/Buenos_Aires", value: "America/Argentina/Buenos_Aires"},
    {id: 39, name: "(GMT-03:00) America/Cordoba", value: "America/Cordoba"},
    {id: 40, name: "(GMT-03:00) America/Fortaleza", value: "America/Fortaleza"},
    {id: 41, name: "(GMT-03:00) America/Montevideo", value: "America/Montevideo"},
    {id: 42, name: "(GMT-03:00) America/Santiago", value: "America/Santiago"},
    {id: 43, name: "(GMT-03:00) America/Sao_Paulo", value: "America/Sao_Paulo"},
    {id: 44, name: "(GMT-03:00) Brasilia", value: "America/Sao_Paulo"},
    {id: 45, name: "(GMT-03:00) Buenos Aires", value: "America/Argentina/Buenos_Aires"},
    {id: 46, name: "(GMT-03:00) Greenland", value: "America/Godthab"},
    {id: 47, name: "(GMT-03:00) Santiago", value: "America/Santiago"},
    {id: 48, name: "(GMT-02:00) Mid-Atlantic", value: "America/Noronha"},
    {id: 49, name: "(GMT-01:00) Azores", value: "Atlantic/Azores"},
    {id: 50, name: "(GMT-01:00) Cape Verde Is.", value: "Atlantic/Cape_Verde"},
    {id: 51, name: "(GMT+00:00) Africa/Casablanca", value: "Africa/Casablanca"},
    {id: 52, name: "(GMT+00:00) Atlantic/Canary", value: "Atlantic/Canary"},
    {id: 53, name: "(GMT+00:00) Atlantic/Reykjavik", value: "Atlantic/Reykjavik"},
    {id: 54, name: "(GMT+00:00) Casablanca", value: "Africa/Casablanca"},
    {id: 55, name: "(GMT+00:00) Dublin", value: "Etc/Greenwich"},
    {id: 56, name: "(GMT+00:00) Edinburgh", value: "Europe/London"},
    {id: 57, name: "(GMT+00:00) Europe/Dublin", value: "Europe/Dublin"},
    {id: 58, name: "(GMT+00:00) Europe/Lisbon", value: "Europe/Lisbon"},
    {id: 59, name: "(GMT+00:00) Europe/London", value: "Europe/London"},
    {id: 60, name: "(GMT+00:00) Lisbon", value: "Europe/Lisbon"},
    {id: 61, name: "(GMT+00:00) London", value: "Europe/London"},
    {id: 62, name: "(GMT+00:00) Monrovia", value: "Africa/Monrovia"},
    {id: 63, name: "(GMT+00:00) UTC", value: "UTC"},
    {id: 64, name: "(GMT+01:00) Amsterdam", value: "Europe/Amsterdam"},
    {id: 65, name: "(GMT+01:00) Belgrade", value: "Europe/Belgrade"},
    {id: 66, name: "(GMT+01:00) Berlin", value: "Europe/Berlin"},
    {id: 67, name: "(GMT+01:00) Bern", value: "Europe/Berlin"},
    {id: 68, name: "(GMT+01:00) Bratislava", value: "Europe/Bratislava"},
    {id: 69, name: "(GMT+01:00) Brussels", value: "Europe/Brussels"},
    {id: 70, name: "(GMT+01:00) Budapest", value: "Europe/Budapest"},
    {id: 71, name: "(GMT+01:00) Copenhagen", value: "Europe/Copenhagen"},
    {id: 72, name: "(GMT+01:00) Europe/Amsterdam", value: "Europe/Amsterdam"},
    {id: 73, name: "(GMT+01:00) Europe/Belgrade", value: "Europe/Belgrade"},
    {id: 74, name: "(GMT+01:00) Europe/Berlin", value: "Europe/Berlin"},
    {id: 75, name: "(GMT+01:00) Europe/Bratislava", value: "Europe/Bratislava"},
    {id: 76, name: "(GMT+01:00) Europe/Brussels", value: "Europe/Brussels"},
    {id: 77, name: "(GMT+01:00) Europe/Budapest", value: "Europe/Budapest"},
    {id: 78, name: "(GMT+01:00) Europe/Copenhagen", value: "Europe/Copenhagen"},
    {id: 79, name: "(GMT+01:00) Europe/Ljubljana", value: "Europe/Ljubljana"},
    {id: 80, name: "(GMT+01:00) Europe/Madrid", value: "Europe/Madrid"},
    {id: 81, name: "(GMT+01:00) Europe/Monaco", value: "Europe/Monaco"},
    {id: 82, name: "(GMT+01:00) Europe/Oslo", value: "Europe/Oslo"},
    {id: 83, name: "(GMT+01:00) Europe/Paris", value: "Europe/Paris"},
    {id: 84, name: "(GMT+01:00) Europe/Podgorica", value: "Europe/Podgorica"},
    {id: 85, name: "(GMT+01:00) Europe/Prague", value: "Europe/Prague"},
    {id: 86, name: "(GMT+01:00) Europe/Rome", value: "Europe/Rome"},
    {id: 87, name: "(GMT+01:00) Europe/Stockholm", value: "Europe/Stockholm"},
    {id: 88, name: "(GMT+01:00) Europe/Tirane", value: "Europe/Tirane"},
    {id: 89, name: "(GMT+01:00) Europe/Vienna", value: "Europe/Vienna"},
    {id: 90, name: "(GMT+01:00) Europe/Warsaw", value: "Europe/Warsaw"},
    {id: 91, name: "(GMT+01:00) Europe/Zagreb", value: "Europe/Zagreb"},
    {id: 92, name: "(GMT+01:00) Europe/Zurich", value: "Europe/Zurich"},
    {id: 93, name: "(GMT+01:00) Ljubljana", value: "Europe/Ljubljana"},
    {id: 94, name: "(GMT+01:00) Madrid", value: "Europe/Madrid"},
    {id: 95, name: "(GMT+01:00) Paris", value: "Europe/Paris"},
    {id: 96, name: "(GMT+01:00) Prague", value: "Europe/Prague"},
    {id: 97, name: "(GMT+01:00) Rome", value: "Europe/Rome"},
    {id: 98, name: "(GMT+01:00) Sarajevo", value: "Europe/Sarajevo"},
    {id: 99, name: "(GMT+01:00) Skopje", value: "Europe/Skopje"},
    {id: 100, name: "(GMT+01:00) Stockholm", value: "Europe/Stockholm"},
    {id: 101, name: "(GMT+01:00) Vienna", value: "Europe/Vienna"},
    {id: 102, name: "(GMT+01:00) Warsaw", value: "Europe/Warsaw"},
    {id: 103, name: "(GMT+01:00) West Central Africa", value: "Africa/Lagos"},
    {id: 104, name: "(GMT+01:00) Zagreb", value: "Europe/Zagreb"},
    {id: 105, name: "(GMT+02:00) Asia/Beirut", value: "Asia/Beirut"},
    {id: 106, name: "(GMT+02:00) Asia/Jerusalem", value: "Asia/Jerusalem"},
    {id: 107, name: "(GMT+02:00) Asia/Nicosia", value: "Asia/Nicosia"},
    {id: 108, name: "(GMT+02:00) Athens", value: "Europe/Athens"},
    {id: 109, name: "(GMT+02:00) Bucharest", value: "Europe/Bucharest"},
    {id: 110, name: "(GMT+02:00) Cairo", value: "Africa/Cairo"},
    {id: 111, name: "(GMT+02:00) Europe/Athens", value: "Europe/Athens"},
    {id: 112, name: "(GMT+02:00) Europe/Helsinki", value: "Europe/Helsinki"},
    {id: 113, name: "(GMT+02:00) Europe/Istanbul", value: "Europe/Istanbul"},
    {id: 114, name: "(GMT+02:00) Europe/Riga", value: "Europe/Riga"},
    {id: 115, name: "(GMT+02:00) Europe/Sofia", value: "Europe/Sofia"},
    {id: 116, name: "(GMT+02:00) Harare", value: "Africa/Harare"},
    {id: 117, name: "(GMT+02:00) Helsinki", value: "Europe/Helsinki"},
    {id: 118, name: "(GMT+02:00) Istanbul", value: "Europe/Istanbul"},
    {id: 119, name: "(GMT+02:00) Jerusalem", value: "Asia/Jerusalem"},
    {id: 120, name: "(GMT+02:00) Kyiv", value: "Europe/Helsinki"},
    {id: 121, name: "(GMT+02:00) Pretoria", value: "Africa/Johannesburg"},
    {id: 122, name: "(GMT+02:00) Riga", value: "Europe/Riga"},
    {id: 123, name: "(GMT+02:00) Sofia", value: "Europe/Sofia"},
    {id: 124, name: "(GMT+02:00) Tallinn", value: "Europe/Tallinn"},
    {id: 125, name: "(GMT+02:00) Vilnius", value: "Europe/Vilnius"},
    {id: 126, name: "(GMT+03:00) Baghdad", value: "Asia/Baghdad"},
    {id: 127, name: "(GMT+03:00) Europe/Minsk", value: "Europe/Minsk"},
    {id: 128, name: "(GMT+03:00) Europe/Moscow", value: "Europe/Moscow"},
    {id: 129, name: "(GMT+03:00) Kuwait", value: "Asia/Kuwait"},
    {id: 130, name: "(GMT+03:00) Minsk", value: "Europe/Minsk"},
    {id: 131, name: "(GMT+03:00) Moscow", value: "Europe/Moscow"},
    {id: 132, name: "(GMT+03:00) Nairobi", value: "Africa/Nairobi"},
    {id: 133, name: "(GMT+03:00) Riyadh", value: "Asia/Riyadh"},
    {id: 134, name: "(GMT+03:00) St. Petersburg", value: "Europe/Moscow"},
    {id: 135, name: "(GMT+03:00) Volgograd", value: "Europe/Volgograd"},
    {id: 136, name: "(GMT+03:30) Tehran", value: "Asia/Tehran"},
    {id: 137, name: "(GMT+04:00) Abu Dhabi", value: "Asia/Muscat"},
    {id: 138, name: "(GMT+04:00) Asia/Dubai", value: "Asia/Dubai"},
    {id: 139, name: "(GMT+04:00) Asia/Tbilisi", value: "Asia/Tbilisi"},
    {id: 140, name: "(GMT+04:00) Baku", value: "Asia/Baku"},
    {id: 141, name: "(GMT+04:00) Muscat", value: "Asia/Muscat"},
    {id: 142, name: "(GMT+04:00) Tbilisi", value: "Asia/Tbilisi"},
    {id: 143, name: "(GMT+04:00) Yerevan", value: "Asia/Yerevan"},
    {id: 144, name: "(GMT+04:30) Kabul", value: "Asia/Kabul"},
    {id: 145, name: "(GMT+05:00) Ekaterinburg", value: "Asia/Yekaterinburg"},
    {id: 146, name: "(GMT+05:00) Indian/Maldives", value: "Indian/Maldives"},
    {id: 147, name: "(GMT+05:00) Islamabad", value: "Asia/Karachi"},
    {id: 148, name: "(GMT+05:00) Karachi", value: "Asia/Karachi"},
    {id: 149, name: "(GMT+05:00) Tashkent", value: "Asia/Tashkent"},
    {id: 150, name: "(GMT+05:30) Asia/Calcutta", value: "Asia/Calcutta"},
    {id: 151, name: "(GMT+05:30) Asia/Colombo", value: "Asia/Colombo"},
    {id: 152, name: "(GMT+05:30) Chennai", value: "Asia/Calcutta"},
    {id: 153, name: "(GMT+05:30) Kolkata", value: "Asia/Kolkata"},
    {id: 154, name: "(GMT+05:30) Mumbai", value: "Asia/Calcutta"},
    {id: 155, name: "(GMT+05:30) New Delhi", value: "Asia/Calcutta"},
    {id: 156, name: "(GMT+05:30) Sri Jayawardenepura", value: "Asia/Calcutta"},
    {id: 157, name: "(GMT+05:45) Kathmandu", value: "Asia/Katmandu"},
    {id: 158, name: "(GMT+06:00) Almaty", value: "Asia/Almaty"},
    {id: 159, name: "(GMT+06:00) Astana", value: "Asia/Dhaka"},
    {id: 160, name: "(GMT+06:00) Dhaka", value: "Asia/Dhaka"},
    {id: 161, name: "(GMT+06:00) Novosibirsk", value: "Asia/Novosibirsk"},
    {id: 162, name: "(GMT+06:00) Urumqi", value: "Asia/Urumqi"},
    {id: 163, name: "(GMT+06:30) Rangoon", value: "Asia/Rangoon"},
    {id: 164, name: "(GMT+07:00) Asia/Bangkok", value: "Asia/Bangkok"},
    {id: 165, name: "(GMT+07:00) Asia/Jakarta", value: "Asia/Jakarta"},
    {id: 166, name: "(GMT+07:00) Bangkok", value: "Asia/Bangkok"},
    {id: 167, name: "(GMT+07:00) Hanoi", value: "Asia/Bangkok"},
    {id: 168, name: "(GMT+07:00) Jakarta", value: "Asia/Jakarta"},
    {id: 169, name: "(GMT+07:00) Krasnoyarsk", value: "Asia/Krasnoyarsk"},
    {id: 170, name: "(GMT+08:00) Asia/Chongqing", value: "Asia/Chongqing"},
    {id: 171, name: "(GMT+08:00) Asia/Hong_Kong", value: "Asia/Hong_Kong"},
    {id: 172, name: "(GMT+08:00) Asia/Kuala_Lumpur", value: "Asia/Kuala_Lumpur"},
    {id: 173, name: "(GMT+08:00) Asia/Macau", value: "Asia/Macau"},
    {id: 174, name: "(GMT+08:00) Asia/Makassar", value: "Asia/Makassar"},
    {id: 175, name: "(GMT+08:00) Asia/Shanghai", value: "Asia/Shanghai"},
    {id: 176, name: "(GMT+08:00) Asia/Taipei", value: "Asia/Taipei"},
    {id: 177, name: "(GMT+08:00) Beijing", value: "Asia/Hong_Kong"},
    {id: 178, name: "(GMT+08:00) Chongqing", value: "Asia/Chongqing"},
    {id: 179, name: "(GMT+08:00) Hong Kong", value: "Asia/Hong_Kong"},
    {id: 180, name: "(GMT+08:00) Irkutsk", value: "Asia/Irkutsk"},
    {id: 181, name: "(GMT+08:00) Kuala Lumpur", value: "Asia/Kuala_Lumpur"},
    {id: 182, name: "(GMT+08:00) Perth", value: "Australia/Perth"},
    {id: 183, name: "(GMT+08:00) Singapore", value: "Asia/Singapore"},
    {id: 184, name: "(GMT+08:00) Taipei", value: "Asia/Taipei"},
    {id: 185, name: "(GMT+08:00) Ulaan Bataar", value: "Asia/Ulan_Bator"},
    {id: 186, name: "(GMT+09:00) Asia/Seoul", value: "Asia/Seoul"},
    {id: 187, name: "(GMT+09:00) Asia/Tokyo", value: "Asia/Tokyo"},
    {id: 188, name: "(GMT+09:00) Osaka", value: "Asia/Tokyo"},
    {id: 189, name: "(GMT+09:00) Sapporo", value: "Asia/Tokyo"},
    {id: 190, name: "(GMT+09:00) Seoul", value: "Asia/Seoul"},
    {id: 191, name: "(GMT+09:00) Tokyo", value: "Asia/Tokyo"},
    {id: 192, name: "(GMT+09:00) Yakutsk", value: "Asia/Yakutsk"},
    {id: 193, name: "(GMT+09:30) Adelaide", value: "Australia/Adelaide"},
    {id: 194, name: "(GMT+09:30) Darwin", value: "Australia/Darwin"},
    {id: 195, name: "(GMT+10:00) Australia/Brisbane", value: "Australia/Brisbane"},
    {id: 196, name: "(GMT+10:00) Australia/Hobart", value: "Australia/Hobart"},
    {id: 197, name: "(GMT+10:00) Australia/Melbourne", value: "Australia/Melbourne"},
    {id: 198, name: "(GMT+10:00) Australia/Sydney", value: "Australia/Sydney"},
    {id: 199, name: "(GMT+10:00) Brisbane", value: "Australia/Brisbane"},
    {id: 200, name: "(GMT+10:00) Canberra", value: "Australia/Canberra"},
    {id: 201, name: "(GMT+10:00) Guam", value: "Pacific/Guam"},
    {id: 202, name: "(GMT+10:00) Hobart", value: "Australia/Hobart"},
    {id: 203, name: "(GMT+10:00) Magadan", value: "Asia/Magadan"},
    {id: 204, name: "(GMT+10:00) Melbourne", value: "Australia/Melbourne"},
    {id: 205, name: "(GMT+10:00) Port Moresby", value: "Pacific/Port_Moresby"},
    {id: 206, name: "(GMT+10:00) Solomon Is.", value: "Asia/Magadan"},
    {id: 207, name: "(GMT+10:00) Sydney", value: "Australia/Sydney"},
    {id: 208, name: "(GMT+10:00) Vladivostok", value: "Asia/Vladivostok"},
    {id: 209, name: "(GMT+11:00) New Caledonia", value: "Asia/Magadan"},
    {id: 210, name: "(GMT+12:00) Auckland", value: "Pacific/Auckland"},
    {id: 211, name: "(GMT+12:00) Fiji", value: "Pacific/Fiji"},
    {id: 212, name: "(GMT+12:00) Kamchatka", value: "Asia/Kamchatka"},
    {id: 213, name: "(GMT+12:00) Marshall Is.", value: "Pacific/Fiji"},
    {id: 214, name: "(GMT+12:00) Pacific/Auckland", value: "Pacific/Auckland"},
    {id: 215, name: "(GMT+12:00) Wellington", value: "Pacific/Auckland"},
    {id: 216, name: "(GMT+13:00) Nuku\'alofa", value: "Pacific/Tongatapu"},
];

export default async () => {
    try {
        console.log('Running Timezone Seeder');
        
        await Timezone.deleteMany({});

        data.forEach(async (item) => {
            await Timezone.create(item);
        });
    }
    catch (error) {
        console.error('Timezone Seeding failed:', error);
    }
};